### ISSUE TITLE
Add option to change resolution density

### ISSUE THREAD

**Issue by adius** [christopherwk210/site-scan#5]
The screenshots are really low density. No comparison to a normal screenshot taken on a retina display. There should definitely be an option to set the density (e.g. `--density 100ppmm`)

**Comment by christopherwk210** [comment]
I'm open to a PR, but I'm not sure if that's possible.

A retina display mac renders everything at a larger size to accommodate the display. Because headless chrome is, well, **headless**, it doesn't render anything to a screen at all. It seems there is no way to "force" it to render like it would on a retina screen either, which makes sense because an option like that wouldn't really have a purpose.

The only solution I can think of is to scale the image after the screenshot is taken, and a feature like that doesn't really belong in this tool.

**Comment by adius** [comment]
> I'm open to a PR, but I'm not sure if that's possible.

Pageres supports it: https://github.com/sindresorhus/pageres#scale

> It seems there is no way to "force" it to render like it would on a retina screen either

I think what should work is zooming into the website with the same factor as scaling the viewport.
I'd also guess that's how pageres does it...

**Comment by christopherwk210** [comment]
Ah yes, that makes much more sense! You're right then, it's definitely possible and I've added the feature in d20bfa26372dc237bf6aa104d7a34be31f6726d4, good suggestion. Updated the npm package as well, closing :)

**Comment by adius** [comment]
Nice, thanks!
(Btw: You messed up the version number a little ... after 1.2.7 comes 1.3.0 and not 1.3.7 😅)

**Comment by adius** [comment]
@christopherwk210 To cite the official specification (https://semver.org/#spec-item-7):

> Patch version MUST be reset to 0 when minor version is incremented.

**Comment by christopherwk210** [comment]
Hey you're right, thank you for the heads up! I had no idea, will do this going forward.
